### PR TITLE
Feature/nginx container

### PR DESCRIPTION
**Pull request by adam-paterson**
## Description

Added Nginx Docker container with vhost configuration from `/docs` repo.

## Motivation and context
* Adds Travis configuration to test docker builds
* Allows Nginx container with default configuration for KickAssCommerce to be used with docker

## How has this been tested?
Tested locally until Travis configuration is complete.

```bash
$ docker-compose --file docker-compose-build.yml up -d
$ docker-compose --file docker-compose-build.yml run web nginx -t
```

## Types of changes

What types of changes does your code introduce? Put an `x` in all the boxes that apply:
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

Go over all the following points, and put an `x` in all the boxes that apply.

Please, please, please, don't send your pull request until all of the boxes are ticked. Once your pull request is created, it will trigger a build on our [continuous integration](http://www.phptherightway.com/#continuous-integration) server to make sure your [tests and code style pass](https://help.github.com/articles/about-required-status-checks/).

- [x] I have read the **[CONTRIBUTING](CONTRIBUTING.md)** document.
- [x] My pull request addresses exactly one patch/feature.
- [x] I have created a branch for this patch/feature.
- [x] Each individual commit in the pull request is meaningful.
- [x] I have added tests to cover my changes.
- [x] If my change requires a change to the documentation, I have updated it accordingly.

### CODE REVIEW

**Review by dmanners — APPROVED** [review]
This all looks great. I don't really understand docker but the nginx stuff looks good.

**Comment by adam-paterson** [comment]
@dmanners I wouldn't worry, nobody understands Docker. Thanks.

**Comment by sandermangel** [comment]
@adam-paterson So are we using one container that has php and nginx installed or will we be using multiple containers? 
I use separate containers for everything myself and the benefit was I can easily add or replace stuff

**Comment by adam-paterson** [comment]
@sandermangel We'll be using separate containers for each individual service required.

This adds the foundation (`docker-compose-build.yml`) which is required to add the other container definitions.

**Pull request merged**
